### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by SgtSobieski** [Memessidy/protonmail-generator#4]
Finding email button and field...
Trying to find a verification code
Something went wrong! Expecting value: line 1 column 1 (char 0)

**Comment by Memessidy** [comment]
Hello! Is this the first time you've had this problem? I can’t repeat it. Can you try again?

**Comment by SgtSobieski** [comment]
Oh thats strange. I didnt comment it as it happens on 4 different machines with different real ips or vpns since approx. a week.

**Comment by Memessidy** [comment]
Thanks for bringing up the issue. I think the problem occurred because the first temporary email (maildrop.cc) was not working at that time. Now I believe I have fixed this problem, but I'm not sure. I mean the program will change the next temporary email in such case. You can download the updated version and try again if you want.

**Comment by SgtSobieski** [comment]
Perfect - works again. Thank you very much!
